@startuml
sprite $sage [48x48/16z] {
nTL5OW0X30NGZtjo_zFMXIdyaLNV6YU2Vs1zY25uPt3DfQw_UlOu4uSkQW0HHBSaOgSg9UiUfkkPPd4qz9nOSXWYO-RrGCOOehE2W-dm8pbySh6IuPQ-HEpw
fk8ewZUBltnVXgFebuIDmBygW23Z4mXo7Z4Wo7t5umQdn_SdQFH8gpd5u2q_4C4oh2ibsM1XXfw8U9Wl3QlqT8B9SfulAr-64WQ42wcqBcG3pjYGfzqwxWZw
0xSaSW76i5Ijxj7u-llhf3Aj6LdDII3A9Y4bygBTZiE_Z6ZmAyesHhFEUedUEUTJrTbI3S_btIToWfaJlU1mO9gU2hUR8ozYMObgi6NIs8rsu6pgEclHu8eD
CRz9SLSENm4
}
@enduml