@startuml
sprite $paper_form [48x48/16z] {
tTPNSiCm34NHnzw1_Uys66f6lT3foVtDYMs95L0-tkSLLXdYfvh2Kk7dCfQOcTfT963h7UuA_z4NsbTlVULzTEkFSo9y-FVhrtpWf6Qlhfgz4aXczxo7yknX
6pUC-Ghu27WxUsFFCzqRA69oey-RWIICHhs6viuMdzk-EliuBS8wE1-SWcF9h7s8Xx3K-fjQ-uSdaDImLom5z9xc0wGifA4tChw6Endr_Ky5Es_TUGP-UPSZ
pwj8GCAmZynCwk1ptJVzPCsIn_3-KFgxFFgGzaL8bYKBFVhxs_Gkow0FB6auEl4QFRMVE15eHs-8cmQGrzzcfdSPBlRF17YMDjv1qS7F3pRDzCLN0tW--Wuj
e3TpI_lh_TO6qqdmFt4UVU2yhlnSmP9zvgInIeTNxZDl
}
@enduml