@startuml
sprite $umbraco [48x48/16] {
00000000000000FFFFFFFFFFFFFFFFFFFF00000000000000
000000000000FFFFFFFFFFFFFFFFFFFFFFFF000000000000
00000000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000
000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000
00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFF
FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFF
FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF
FFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFF
FFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFF
FFFFFFFFFFFF000FFFFFFFFFFFFFFFFFF000FFFFFFFFFFFF
FFFFFFFFFFFFF0000FFFFFFFFFFFFFF0000FFFFFFFFFFFFF
FFFFFFFFFFFFFF00000000000000000000FFFFFFFFFFFFF0
0FFFFFFFFFFFFFFF0000000000000000FFFFFFFFFFFFFFF0
0FFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFF00
00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00
000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000
0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000
000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000000
0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000
00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00000000
000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF0000000000
00000000000FFFFFFFFFFFFFFFFFFFFFFFFFF00000000000
000000000000FFFFFFFFFFFFFFFFFFFFFFFF000000000000
00000000000000FFFFFFFFFFFFFFFFFFFF00000000000000
}
@enduml